import json
import xml.dom.minidom
from bs4 import BeautifulSoup


def format_response(content: str, content_type: str = "") -> str:
    """Formats/Pretty-prints JSON, HTML, XML, or falls back to plain text."""
    if not content or not isinstance(content, str):
        return ""

    raw_text = content.strip()
    content_type = content_type.lower()

    # 1. JSON Formatting
    if ("json" in content_type) or (raw_text.startswith("{") and raw_text.endswith("}")) or (raw_text.startswith("[") and raw_text.endswith("]")):
        try:
            parsed = json.loads(raw_text)
            return json.dumps(parsed, indent=2, ensure_ascii=False)
        except Exception:
            pass

    # 2. HTML Formatting (Beautifies minified HTML + indent scripts/tags)
    if ("html" in content_type) or (raw_text.startswith("<!doctype") or raw_text.startswith("<html")):
        try:
            soup = BeautifulSoup(raw_text, "html.parser")
            return soup.prettify()
        except Exception:
            pass

    # 3. XML Formatting
    if ("xml" in content_type) or (raw_text.startswith("<?xml") or (raw_text.startswith("<") and raw_text.endswith(">"))):
        try:
            dom = xml.dom.minidom.parseString(raw_text)
            # Removes empty excess blank lines generated by minidom
            pretty_xml = dom.toprettyxml(indent="  ")
            return "\n".join([
                line for line in pretty_xml.splitlines() if line.strip()
            ])
        except Exception:
            pass

    # Fallback to unmodified text
    return content